Repository 01-edu/public, pull requests merged in 2023-02, with the labels that each got.

#1795 DEV-4422-add-pictures-to-deep-in-system-repo
  subjects/devops/deep-in-system/README.md
  subjects/devops/deep-in-system/pictures/sysadmin.jpeg
Labels: 🗂️ documentation

#1796 DEV-4430 Add `runner` v2 support
  sh/debian/configure.sh
Labels: 🪄 feature

#1829 DEV-4475 Renaming css files to data.css for all dom exercises
  subjects/build-brick-and-break/README.md
  subjects/build-brick-and-break/build-brick-and-break.data.css
  subjects/build-brick-and-break/build-brick-and-break.html
  subjects/fifty-shades-of-cold/README.md
  subjects/fifty-shades-of-cold/fifty-shades-of-cold.data.css
  subjects/fifty-shades-of-cold/fifty-shades-of-cold.html
  subjects/get-them-all/README.md
  subjects/get-them-all/get-them-all.data.css
  subjects/get-them-all/get-them-all.html
  subjects/gossip-grid/README.md
  subjects/gossip-grid/gossip-grid.data.css
  subjects/gossip-grid/gossip-grid.html
  subjects/harder-bigger-bolder-stronger/README.md
  subjects/harder-bigger-bolder-stronger/harder-bigger-bolder-stronger.data.css
  subjects/harder-bigger-bolder-stronger/harder-bigger-bolder-stronger.html
  subjects/keycodes-symphony/README.md
  subjects/keycodes-symphony/keycodes-symphony.data.css
  subjects/keycodes-symphony/keycodes-symphony.html
  subjects/mouse-trap/README.md
  subjects/mouse-trap/mouse-trap.data.css
  subjects/mouse-trap/mouse-trap.html
  subjects/pick-and-click/README.md
  subjects/pick-and-click/pick-and-click.data.css
  subjects/pick-and-click/pick-and-click.html
  subjects/pimp-my-style/README.md
  subjects/pimp-my-style/pimp-my-style.data.css
  subjects/pimp-my-style/pimp-my-style.html
  subjects/where-do-we-go/README.md
  subjects/where-do-we-go/where-do-we-go.data.css
  subjects/where-do-we-go/where-do-we-go.html
Labels: 🐛 bug

#1831 fix(harder-bigger-bolder-stronger): add right css file to html
  subjects/harder-bigger-bolder-stronger/harder-bigger-bolder-stronger.html
Labels: 🐛 bug
