Repository 01-edu/public, pull requests merged in 2023-05, with the labels that each got.

#2008 DEV-4987-fix-orchestrator-architecture-error
  subjects/devops/orchestrator/README.md
  subjects/devops/orchestrator/audit/README.md
  subjects/devops/orchestrator/pictures/Architecture.png
Labels: 🗂️ documentation

#2007 DEV-4981-fix-deep-in-system-visible-password
  subjects/devops/deep-in-system/README.md
  subjects/devops/deep-in-system/audit/README.md
Labels: 🗂️ documentation, 🐛 bug

#2003 DEV-4972-make-terraform-mandatory
  subjects/devops/cloud-design/README.md
  subjects/devops/cloud-design/audit/README.md
Labels: 🗂️ documentation

#2041 DEV-502 Fix audit requests for `ascii-art color`
  subjects/ascii-art/color/audit.md
Labels: 🐛 bug
