Repository 01-edu/public, pull requests merged in 2024-11, with the labels that each got.

#2795 DEV-6244 Add internal PR compliance checks
  .github/workflows/ga-misc-check-compliance.yml
Labels: 🪄 feature

#2807 CON-3263 Fix subjects
  subjects/go-reloaded/README.md
  subjects/wget/README.md
  subjects/wget/audit/README.md
Labels: 🤸 skip-check-links

#2800 [EXTERNAL] fix audit readme file posts/comments
  subjects/forum/audit/README.md
Labels: 🗂️ docs

#2663 [EXTERNAL] Fixing a few minor things in subjects from the RUST piscine
  subjects/borrow_box/README.md
  subjects/nextprime/README.md
  subjects/previousprime/README.md
  subjects/prime_checker/README.md
  subjects/scores/README.md
Labels: Rust

#2809 CON-3267 Improve `brainfuck` instructions
  subjects/brainfuck/README.md
Labels: 🗂️ docs
