Repository 01-edu/public, pull requests merged in 2024-05, with the labels that each got.

#2564 CON-2696 Update `quadchecker` subject
  subjects/quadchecker/README.md
Labels: 🗂️ docs

#2572 CON-2701 add flag to `wget` subject
  subjects/wget/README.md
Labels: 🤸 skip-check-links

#2575 CON-2705 Adding Main Files To The CheckPoints
  subjects/java/checkpoints/almost-palindrom/ExerciseRunner.java
  subjects/java/checkpoints/average-calc/ExerciseRunner.java
  subjects/java/checkpoints/count-char/ExerciseRunner.java
  subjects/java/checkpoints/digitlen/ExerciseRunner.java
  subjects/java/checkpoints/factorial/ExerciseRunner.java
  subjects/java/checkpoints/goodbye-mars/ExerciseRunner.java
  subjects/java/checkpoints/multiplication-table/ExerciseRunner.java
  subjects/java/checkpoints/next-prime/ExerciseRunner.java
  subjects/java/checkpoints/reverse-array/ExerciseRunner.java
  subjects/java/checkpoints/rotate-array/ExerciseRunner.java
  subjects/java/checkpoints/sort-array/ExerciseRunner.java
  subjects/java/checkpoints/strlen/ExerciseRunner.java
  subjects/java/checkpoints/system-logger/ExerciseRunner.java
  subjects/java/checkpoints/unit-converter/ExerciseRunner.java
  subjects/java/checkpoints/universal-greeting/ExerciseRunner.java
Labels: 🗂️ docs

#2573 CON-2703 update expected output in `pig_latin` subject to be inline with description
  subjects/pig_latin/README.md
Labels: 🗂️ docs

#2582 CON-2717 Fix Digitlen Main issue
  subjects/java/checkpoints/digitlen/ExerciseRunner.java
Labels: 🐛 bug
