Repository 01-edu/public, pull requests merged in 2024-12, with the labels that each got.

#2814 CON-3280 refactor `social-network`
  subjects/social-network/README.md
  subjects/social-network/audit/README.md
Labels: 🗂️ docs

#2815 DEV-6316 fix: issue-with-exercise-crud-master-instructions-and-file-structure
  subjects/devops/crud-master-py/README.md
Labels: 📕 DevOps

#2822 [EXTERNAL] Improve `groupie-tracker` project description
  subjects/groupie-tracker/README.md
Labels: 🗂️ docs

#2818 CON-3289 Improve subjects
  subjects/ascii-art-web/stylize/audit.md
  subjects/ascii-art-web/stylize/audit/README.md
  subjects/ascii-art/audit/README.md
  subjects/ascii-art/fs/audit/README.md
  subjects/ascii-art/justify/audit/README.md
  subjects/ascii-art/reverse/audit/README.md
  subjects/forum/advanced-features/audit.md
  subjects/forum/advanced-features/audit/README.md
  subjects/forum/audit/README.md
  subjects/forum/security/audit.md
  subjects/forum/security/audit/README.md
  subjects/groupie-tracker/audit/README.md
  subjects/groupie-tracker/visualizations/audit.md
  subjects/groupie-tracker/visualizations/audit/README.md
  subjects/make-your-game/audit/README.md
  subjects/make-your-game/different-maps/audit.md
  subjects/make-your-game/different-maps/audit/README.md
  subjects/make-your-game/history/audit.md
  subjects/make-your-game/history/audit/README.md
  subjects/make-your-game/score-handling/audit.md
  subjects/make-your-game/score-handling/audit/README.md
  subjects/mini-framework/audit/README.md
  subjects/my-ls-1/audit/README.md
  subjects/my-ls/audit/README.md
  subjects/net-cat/audit/README.md
  subjects/tetris-optimizer/audit/README.md
  subjects/wget/audit/README.md
Labels: 🗂️ docs, 🤸 skip-check-links

#2811 CON-3260 Fix rust piscine's quest-01
  subjects/division_and_remainder/README.md
  subjects/fibonacci2/README.md
  subjects/find_factorial/README.md
  subjects/groceries/README.md
  subjects/looping/README.md
  subjects/matrix_transposition/README.md
  subjects/reverse_string/README.md
  subjects/scalar/README.md
  subjects/speed_transformation/README.md
  subjects/temperature_conv/README.md
  subjects/tuples_refs/README.md
Labels: 📕 Rust

#2824 [EXTERNAL] Project `net-cat`: Remove confusing quotes
  subjects/net-cat/audit/README.md
Labels: 🗂️ docs

#2490 [EXTERNAL] undefine eval() for elementary.js
  js/tests/elementary_test.js
  subjects/elementary/README.md
Labels: 📕 JS

#2475 [EXTERNAL] add strings to forbidden
  subjects/cybersecurity/hole-in-bin/README.md
Labels: 🗂️ docs, 📕 Cyber Security

#1760 [EXTERNAL] Condition in tests but not in task description
  subjects/pick-omit/README.md
Labels: 🗂️ docs

#2791 CON-3221 Fix the class-it test so it accepts reverted order of classes
  dom/class-it_test.js
Labels: 🧪 test, 📕 DOM
