Repository 01-edu/public, pull requests merged in 2024-07, with the labels that each got.

#2619 CON-2867 Update-subject-of `phant0m-writ3r`
  subjects/phant0m-writ3r/README.md
Labels: 🗂️ docs

#2639 CON-2800 Markdown `Quest00/Ex00`
  dom/the_skeleton_test.js
  subjects/DPxAI/the_skeleton/README.md
Labels: 🗂️ docs

#2629 CON-2911 Markdown Perfect Number Exercise
  subjects/java/checkpoints/perfect-number/ExerciseRunner.java
  subjects/java/checkpoints/perfect-number/README.md
Labels: 🗂️ docs

#2630 CON-2908 Markdown Armstrong Number Exercise
  subjects/java/checkpoints/armstrong-number/ExerciseRunner.java
  subjects/java/checkpoints/armstrong-number/README.md
Labels: 🗂️ docs

#2628 CON-2893 Markdown Builder Blueprint Exercise
  subjects/java/checkpoints/builder-blueprint/ExerciseRunner.java
  subjects/java/checkpoints/builder-blueprint/README.md
Labels: 🗂️ docs

#2621 CON-2875 Markdown Monthly Period
  subjects/java/checkpoints/monthly-period/ExerciseRunner.java
  subjects/java/checkpoints/monthly-period/README.md
Labels: 🗂️ docs

#2626 CON-2887 Markdown Singleton Blueprint Exercise
  subjects/java/checkpoints/singleton-blueprint/ExerciseRunner.java
  subjects/java/checkpoints/singleton-blueprint/README.md
Labels: 🗂️ docs

#2631 CON-2905 Markdown Valid Sudoku Exercise
  subjects/java/checkpoints/valid-sudoku/ExerciseRunner.java
  subjects/java/checkpoints/valid-sudoku/README.md
Labels: 🗂️ docs

#2651 CON-2982 Fix subject rendering for `has-city` exercise
  subjects/has-city/README.md
Labels: 🐛 bug

#2646 CON-2950 Markdown ``DPxAI:Quest00/Ex02``
  subjects/DPxAI/select-then-style/README.md
Labels: 🗂️ docs

#2648 CON-2965 Markdown ``DPxAI:Quest00/Ex03``
  subjects/DPxAI/embedded-organs/README.md
Labels: 🗂️ docs

#2649 CON-2966 Tests ``DPxAI:Quest00/Ex03``
  dom/embedded-organs_test.js
Labels: 🪄 feature, 🧪 test

#2659 CON-3015 Update `printif` and `printifnot` examples to be coherent with subject
  subjects/printif/README.md
  subjects/printifnot/README.md
Labels: 🗂️ docs
