Repository 01-edu/public, pull requests merged in 2024-09, with the labels that each got.

#2703 CON-3109 Add subject for ``Quest03/robots-harmony``
  subjects/DPxAI/robots-harmony/README.md
Labels: 🗂️ docs, 🤸 skip-check-links, DP

#2709 CON-3110 Add audit file ``Quest03/robots-harmony``
  subjects/DPxAI/robots-harmony/audit/README.md
Labels: 🗂️ docs

#2704 CON-3128 Fixing subject ``AI/kaggle-titanic``
  subjects/ai/kaggle-titanic/README.md
Labels: 🗂️ docs, AI

#2713 CON-3006 subject for ``Quest01/play-with-variables``
  subjects/DPxAI/play-with-variables/README.md
Labels: 🗂️ docs

#2705 CON-2931 Resolve missing assets for `stealth-boom` project
  subjects/gaming/stealth-boom/README.md
  subjects/gaming/stealth-boom/audit/README.md
  subjects/gaming/stealth-boom/resources/mgsmeme.png
Labels: 🗂️ docs, 🤸 skip-check-links, Game Dev

#2711 CON-3136 Fix ``AI/SP500-strategies``
  subjects/ai/sp500-strategies/README.md
Labels: 📕 AI

#2736 CON-3181: Change the name of dpxai to `AI.GO`
  subjects/AI.GO/call-it/README.md
  subjects/AI.GO/class-it/README.md
  subjects/AI.GO/colorful-arms/README.md
  subjects/AI.GO/colorful-legs/README.md
  subjects/AI.GO/declare-everything/README.md
  subjects/AI.GO/embedded-organs/README.md
  subjects/AI.GO/first-function/README.md
  subjects/AI.GO/first-hello/README.md
  subjects/AI.GO/first-move/README.md
  subjects/AI.GO/first-wink/README.md
  subjects/AI.GO/glance-on-power/README.md
  subjects/AI.GO/good-recipe/README.md
  subjects/AI.GO/i-win-arguments/README.md
  subjects/AI.GO/listed/README.md
  subjects/AI.GO/objects-around/README.md
  subjects/AI.GO/only-if/README.md
  subjects/AI.GO/play-with-variables/README.md
  subjects/AI.GO/robots-harmony/README.md
  subjects/AI.GO/robots-harmony/audit/README.md
  subjects/AI.GO/select-then-style/README.md
  subjects/AI.GO/star-forge/README.md
  subjects/AI.GO/the-skeleton/README.md
  subjects/AI.GO/the-smooth-operator/README.md
  subjects/AI.GO/transform-objects/README.md
Labels: 🤸 skip-check-links

#2742 DEV-#### Review of subject of the third quest and RAID of AI piscine
  subjects/AI.GO/colorful-arms/README.md
  subjects/AI.GO/robots-harmony/README.md
Labels: 🤸 skip-check-links, 📕 AI
