Repository 01-edu/public, pull requests merged in 2024-10, with the labels that each got.

#2757 CON-#### [update] AI.GO first-hello video link
  subjects/AI.GO/first-hello/README.md
Labels: 🗂️ docs

#2756 CON-#### [update] AI.GO first-wink video link
  subjects/AI.GO/first-wink/README.md
Labels: 🗂️ docs, 🤸 skip-check-links

#2755 CON-#### [update] AI.GO colorful-arms video link
  subjects/AI.GO/colorful-arms/README.md
Labels: 🗂️ docs, 🤸 skip-check-links

#2754 CON-#### [update] AI.GO colorful-legs video link
  subjects/AI.GO/colorful-legs/README.md
Labels: 🗂️ docs, 🤸 skip-check-links

#2738 CON-3182 Fixing instructions issue in `AI.GO/listed`
  subjects/AI.GO/listed/README.md
Labels: 🗂️ docs, 📕 AI

#2739 CON-3183 Fixing instructions in `AI.GO/only-if`
  subjects/AI.GO/only-if/README.md
Labels: 🗂️ docs, 📕 AI

#2765 CON-3142 Refining firing-range project
  subjects/gaming/firing-range/README.md
  subjects/gaming/firing-range/audit/README.md
  subjects/gaming/firing-range/resources/example1.jpg
  subjects/gaming/firing-range/resources/example2.jpg
  subjects/gaming/firing-range/resources/fgm.jpg
Labels: 🗂️ docs, 🤸 skip-check-links, 📕 Game Dev
