Repository 01-edu/public, pull requests merged in 2025-01, with the labels that each got.

#2834 fix(rust-roman_numbers): remove conflicting traits from expected data structure
  subjects/roman_numbers/README.md
Labels: 🐞 bug, 📕 Rust

#2850 CON-3344 fix typo in crud master success code 201 to 200
  subjects/devops/crud-master-py/audit/README.md
Labels: 🗂️ docs, 🐞 bug

#2832 CON-3265 Fix rust piscine's quest-03
  subjects/arrays/README.md
  subjects/bigger/README.md
  subjects/capitalizing/README.md
  subjects/card_deck/README.md
  subjects/changes/README.md
  subjects/circle/README.md
  subjects/collect/README.md
  subjects/edit_distance/README.md
  subjects/hashing/README.md
  subjects/is_anagram/README.md
  subjects/simple_hash/README.md
  subjects/string_permutation/README.md
  subjects/strings/README.md
Labels: 📕 Rust

#2859 CON-3385 Add lacking AI projects and update structure
  subjects/ai/classification/README.md
  subjects/ai/classification/audit/README.md
  subjects/ai/data-wrangling/README.md
  subjects/ai/data-wrangling/audit/README.md
  subjects/ai/document-categorization/README.md
  subjects/ai/document-categorization/audit/README.md
  subjects/ai/emotions-detector/audit/README.md
  subjects/ai/forest-prediction/README.md
  subjects/ai/keras-2/README.md
  subjects/ai/keras-2/audit/README.md
  subjects/ai/keras/README.md
  subjects/ai/keras/audit/README.md
  subjects/ai/linear-regression/README.md
  subjects/ai/linear-regression/audit/README.md
  subjects/ai/matrix-factorization/README.md
  subjects/ai/matrix-factorization/audit/README.md
  subjects/ai/matrix-factorization/readme_data.md
  subjects/ai/model-selection/README.md
  subjects/ai/model-selection/audit/README.md
  subjects/ai/neural-networks/README.md
  subjects/ai/neural-networks/audit/README.md
  subjects/ai/nlp-spacy/README.md
  subjects/ai/nlp-spacy/audit/README.md
  subjects/ai/nlp/README.md
  subjects/ai/nlp/audit/README.md
  subjects/ai/numpy/README.md
  subjects/ai/numpy/audit/README.md
  subjects/ai/pandas/README.md
  subjects/ai/pandas/audit/README.md
  subjects/ai/pipeline/README.md
  subjects/ai/pipeline/audit/README.md
  subjects/ai/spectral-learning/README.md
  subjects/ai/spectral-learning/audit/README.md
  subjects/ai/time-series/README.md
  subjects/ai/time-series/audit/README.md
  subjects/ai/training/README.md
  subjects/ai/training/audit/README.md
  subjects/ai/vision-track/README.md
  subjects/ai/vision-track/audit/README.md
  subjects/ai/visualizations/README.md
  subjects/ai/visualizations/audit/README.md
Labels: 🤸 skip-check-links, 📕 AI

#2862 fix(rust-quest03): re-added removed subjects
  subjects/is_anagram/README.md
  subjects/strings/README.md
Labels: 📕 Rust

#2856 CON-3382 Fix ink in `make your game`
  subjects/make-your-game/README.md
Labels: 🗂️ docs

#2855 CON-3381 `Shoppinglistsort` add package piscine to the main func
  subjects/shoppinglistsort/README.md
Labels: 🗂️ docs

#2854 CON-3380 `Road Intersection` remove bad link
  subjects/road_intersection/README.md
Labels: 🗂️ docs
