Repository 01-edu/public, pull requests merged in 2025-02, with the labels that each got.

#2868 [EXTERNAL] `forum` Fix typos and some grammar
  subjects/forum/audit/README.md
Labels: 🗂️ docs

#2877 [EXTERNAL] `make-your-game` Alternative to a not found (404) resource
  subjects/make-your-game/README.md
Labels: 🗂️ docs, 🤸 skip-check-links

#2872 [EXTERNAL] `forum` and `real-time-forum`: Allow both gofrs/uuid and google/uuid
  subjects/forum/README.md
  subjects/forum/advanced-features/README.md
  subjects/forum/authentication/README.md
  subjects/forum/image-upload/README.md
  subjects/forum/moderation/README.md
  subjects/forum/security/README.md
  subjects/real-time-forum/README.md
  subjects/real-time-forum/typing-in-progress/README.md
Labels: 🗂️ docs, 🤸 skip-check-links

#2875 [EXTERNAL] fix small typo `forum/audit`
  subjects/forum/audit/README.md
Labels: 🗂️ docs, 🤸 skip-check-links

#2837 [EXTERNAL] add rest employment task for software engineers
  employment-tasks/software-engineer/rest-task/README.md
Labels: 🗂️ docs, 🤸 skip-check-links, 📕 Software Engineering

#2828 CON-3314 Improve `deep-in-system` audit for macOS students
  subjects/devops/deep-in-system/README.md
  subjects/devops/deep-in-system/audit/README.md
Labels: 📕 DevOps

#2889 [EXTERNAL] Add links to valuable resource: `forum`, `real-time-forum`, `social-network`
  subjects/forum/README.md
  subjects/forum/authentication/README.md
  subjects/forum/security/README.md
  subjects/real-time-forum/README.md
  subjects/social-network/README.md
Labels: 🗂️ docs, 🤸 skip-check-links

#2892 DEV-6587: Cybersecurity hole in bin SHA1 don't match
  subjects/cybersecurity/hole-in-bin/README.md
Labels: 🤸 skip-check-links, 📕 Cyber Security
