Repository 01-edu/public, pull requests merged in 2025-07, with the labels that each got.

#2961 [EXTERNAL] docs(`mini-framework`): fix subject and audit file
  subjects/mini-framework/README.md
  subjects/mini-framework/audit/README.md
Labels: 🗂️ docs

#2947 CON-3449 Fix `quest-07`
  subjects/borrow_box/README.md
  subjects/bowling_score/README.md
  subjects/box_it/README.md
  subjects/box_recursion/README.md
  subjects/drop_the_thread/README.md
  subjects/how_many_references/README.md
  subjects/ref_cell/README.md
Labels: 📕 Rust

#2952 DEV-6758 Some bugs in java exam files and tests
  subjects/java/checkpoints/singleton-blueprint/ExerciseRunner.java
  subjects/java/checkpoints/singleton-blueprint/README.md
Labels: 🐞 bug

#3008 [EXTERNAL] docs(`matrix-transposition`): precise title highlighting in notions links
  subjects/matrix_transposition/README.md
Labels: 🗂️ docs, 📕 Rust

#3010 [EXTERNAL] docs(modify-letter): Changed to the correct output
  subjects/modify_letter/README.md
Labels: 📕 Rust
