Repository 01-edu/public, pull requests merged in 2025-03, with the labels that each got.

#2890 CON-3397 `Ascii-art-web-dockerize` add missing question
  subjects/ascii-art-web/dockerize/audit.md
  subjects/ascii-art-web/dockerize/audit/README.md
Labels: 🤸 skip-check-links

#2887 CON-3318 Fix rust piscine's quest-04
  subjects/banner/README.md
  subjects/boxing_todo/README.md
  subjects/cipher/README.md
  subjects/error_types/README.md
  subjects/handling/README.md
  subjects/panic/README.md
  subjects/profanity_filter/README.md
  subjects/question_mark/README.md
  subjects/unwrap_or_expect/README.md
Labels: 📕 Rust

#2908 DEV-6628-Deep-in-net-audit-issue
  subjects/devops/deep-in-net/audit/README.md
Labels: 🗂️ docs

#2891 [EXTERNAL] `more-or-less` Align with the exercise's test
  subjects/more-or-less/README.md
Labels: 🗂️ docs, 🤸 skip-check-links

#2893 [EXTERNAL] `forum-security` Remove redundant question
  subjects/forum/security/audit.md
  subjects/forum/security/audit/README.md
Labels: 🗂️ docs, 🤸 skip-check-links

#2894 [EXTERNAL] `make-your-game:score-handling` WebSocket package is not needed
  subjects/make-your-game/score-handling/README.md
Labels: 🗂️ docs, 🤸 skip-check-links

#2899 [EXTERNAL] `ascii-art-web-dockerize` Mimic expected outputs
  subjects/ascii-art-web/dockerize/audit/README.md
Labels: 🗂️ docs, 🤸 skip-check-links
