Repository 01-edu/public, pull requests merged in 2025-08, with the labels that each got.

#3017 CON-3606-Fix-make-your-game-score-handling-inconsistency-between-audit-and-subject
  subjects/make-your-game/score-handling/audit/README.md
Labels: 🐞 bug

#2920 [EXTERNAL]: docs(`typing-in-progress`): refine audit file
  subjects/real-time-forum/typing-in-progress/audit.md
  subjects/real-time-forum/typing-in-progress/audit/README.md
Labels: 🗂️ docs, 🤸 skip-check-links

#3007 [EXTERNAL] clarified phrasing and fixed grammar
  subjects/ascii-art-web/README.md
Labels: 🗂️ docs

#3027 [EXTERNAL] fix(`box_recursion`): fix expected code
  subjects/box_recursion/README.md
Labels: 📕 Rust

#3018 [EXTERNAL] docs(rust-piscine): fix small typos
  subjects/get_document_id/README.md
  subjects/rot21/README.md
Labels: 🗂️ docs, 📕 Rust

#3046 [EXTERNAL] fix(keras-2): correct typo in README (no → not and go → goal)
  subjects/ai/keras-2/README.md
Labels: 🗂️ docs, 🤸 skip-check-links

#3048 [EXTERNAL] docs(keras2): use categorical_crossentropy for single-label multi-class
  subjects/ai/keras-2/README.md
  subjects/ai/numpy/README.md
Labels: 🗂️ docs, 🤸 skip-check-links
