Repository 01-edu/public, pull requests merged in 2025-04, with the labels that each got.

#2913 CON-3429 `Piscine` small fixes
  subjects/firstrune/README.md
  subjects/firstrune/main.go
  subjects/lastrune/README.md
  subjects/lastrune/main.go
  subjects/listforeachif/README.md
  subjects/nrune/README.md
  subjects/printnbr/README.md
  subjects/printnbrbase/README.md
  subjects/rot14/README.md
Labels: 🗂️ docs

#2918 CON-3435 Fix `simple_hash` subject
  subjects/simple_hash/README.md
Labels: 📕 Rust

#2925 CON-3438 Fix `profanity_filter` subject
  subjects/profanity_filter/README.md
Labels: 📕 Rust

#2927 CON-3442 Fix `handling` subject
  subjects/handling/README.md
Labels: 📕 Rust

#2909 CON-3319 Fix `quest-05`
  subjects/does_it_fit/README.md
  subjects/expected_variable/README.md
  subjects/invert_sentence/README.md
  subjects/macro_calculator/README.md
  subjects/middle_day/README.md
  subjects/mobs/README.md
  subjects/shopping_mall/README.md
Labels: 🤸 skip-check-links, 📕 Rust

#2933 CON-3429 Add clarification to `pronoun`
  subjects/pronoun/README.md
Labels: 📕 JS

#2934 CON-3451 add Javascript Checkpoint exercises to the public repo
  subjects/js-array-chunk-reversal/README.md
  subjects/js-bubble-sort-analyzer/README.md
  subjects/js-character-maker/README.md
  subjects/js-deep-clone/README.md
  subjects/js-deep-equal/README.md
  subjects/js-deep-find/README.md
  subjects/js-deep-freeze/README.md
  subjects/js-divisor-finder/README.md
  subjects/js-election-mix/README.md
  subjects/js-even-sum/README.md
  subjects/js-exam-grader/README.md
  subjects/js-factorial/README.md
  subjects/js-fibonacci/README.md
  subjects/js-final-attempt/README.md
  subjects/js-flat-object/README.md
  subjects/js-flatten-object/README.md
  subjects/js-grid-word-finder/README.md
  subjects/js-grid-word-finder2/README.md
  subjects/js-insertion-sort-analyzer/README.md
  subjects/js-nested-array-reverser/README.md
  subjects/js-object-lab/README.md
  subjects/js-palindromic-chains/README.md
  subjects/js-perfect-num/README.md
  subjects/js-pipeline/README.md
  subjects/js-sentence-pyramid/README.md
  subjects/js-sleep-breaker/README.md
  subjects/js-snakepath-validator/README.md
  subjects/js-swappable-object/README.md
  subjects/js-transform-keys/README.md
  subjects/js-trap-object/README.md
  subjects/js-zoo-race/README.md
Labels: 📕 JS

#2938 CON-3456 Improve `0-shell`
  subjects/0-shell/README.md
Labels: 📕 Rust

#2941 CON-3462 Fix `card_deck`
  subjects/card_deck/README.md
Labels: 📕 Rust

#2944 [EXTERNAL] fix(`net-cat`): remove confusing quotes
  subjects/net-cat/audit/README.md
Labels: 🗂️ docs

#2939 [EXTERNAL] refine(`LastWord`): fix backticks
  subjects/lastword/README.md
Labels: 🗂️ docs

#2930 [EXTERNAL]: doc(`shop`): fix readme title
  subjects/shop/README.md
Labels: 🗂️ docs
